const FALLBACK_FR: Record<string, string> = {
  'hero.laverie': 'Laverie',
  'hero.digitale': 'Digitale',
  'hero.premium': 'Premium',
  'hero.dakar': 'à Dakar',
  'hero.subtitle': 'Déposez votre linge, nous faisons le reste. Une expérience de lavage connectée, rapide et fiable.',
  'hero.cta_offres': 'Voir nos offres',
  'hero.cta_paiement': 'Paiement en ligne',
  'features.badge': 'Pourquoi nous choisir',
  'features.title': 'Une laverie intelligente à votre service',
  'features.subtitle': 'Nous combinons technologie de pointe et service premium pour vous offrir la meilleure expérience de lavage à Dakar.',
  'features.cards.0.title': 'Paiement Mobile',
  'features.cards.0.desc': 'Payez en toute sécurité depuis votre téléphone via Wave, Orange Money, Free Money ou carte bancaire. Plus besoin d\'espèces.',
  'features.cards.1.title': 'Suivi en Temps Réel',
  'features.cards.1.desc': 'Recevez des notifications à chaque étape : lavage, séchage, pliage. Vous savez exactement quand votre linge est prêt.',
  'features.cards.2.title': 'Qualité Premium',
  'features.cards.2.desc': 'Machines industrielles de pointe, détergents hypoallergéniques et cycles adaptés à chaque type de tissu. Un résultat impeccable à chaque fois.',
  'features.cards.3.title': 'Service Rapide',
  'features.cards.3.desc': 'Lavage express en 45 minutes ou service standard. Notre système optimisé réduit votre temps d\'attente au minimum.',
  'steps.badge': 'Comment ça marche',
  'steps.title': 'Trois étapes simples pour un linge impeccable',
  'steps.list.0.title': '1. Choisissez votre formule',
  'steps.list.0.desc': 'Sélectionnez le service qui vous convient : lavage simple, lavage-repassage ou nettoyage à sec. Indiquez le poids de votre linge.',
  'steps.list.1.title': '2. Déposez votre linge',
  'steps.list.1.desc': 'Apportez votre linge à notre laverie. Nos agents le pèsent, l\'étiquettent et le prennent en charge immédiatement.',
  'steps.list.2.title': '3. Récupérez-le frais et plié',
  'steps.list.2.desc': 'Recevez une notification quand c\'est prêt. Venez récupérer votre linge parfaitement lavé, séché et plié. Simple comme bonjour.',
  'offers.badge': 'Nos offres',
  'offers.title': 'Des formules adaptées à tous vos besoins',
  'offers.new': 'Nouveau',
  'offers.cards.0.title': 'Lavage Simple',
  'offers.cards.0.desc': 'Lavage, séchage et pliage. Idéal pour le quotidien. À partir de 2 500 FCFA.',
  'offers.cards.1.title': 'Lavage + Repassage',
  'offers.cards.1.desc': 'Lavage, séchage et repassage professionnel. Parfait pour vos chemises et vêtements de travail. À partir de 4 000 FCFA.',
  'offers.cards.2.title': 'Nettoyage à Sec',
  'offers.cards.2.desc': 'Traitement délicat pour vos vêtements fragiles et costumes. Résultat impeccable garanti. À partir de 6 000 FCFA.',
  'testimonials.badge': 'Témoignages',
  'testimonials.title': 'Ce que nos clients disent de nous',
  'testimonials.list.0.author': 'Aminata S.',
  'testimonials.list.0.text': 'Enfin une laverie fiable à Dakar ! Je peux payer depuis Wave et suivre ma commande en temps réel. Le linge est toujours parfaitement plié. Je recommande vivement.',
  'testimonials.list.1.author': 'Moussa D.',
  'testimonials.list.1.text': 'Le service de lavage-repassage est excellent. Mes chemises n\'ont jamais été aussi bien repassées. Et la rapidité est incroyable : 45 minutes montre en main.',
  'testimonials.list.2.author': 'Fatou K.',
  'testimonials.list.2.text': 'Je suis une cliente fidèle depuis l\'ouverture. La qualité du nettoyage à sec est remarquable. Mes robes fragiles sont traitées avec beaucoup de soin. Merci Bellissima !',
  'vision.badge': 'Notre vision',
  'vision.title': 'Réinventer la laverie à Dakar',
  'vision.confiance_title': 'Confiance',
  'vision.confiance_desc': 'La transparence est au cœur de notre engagement. Paiement sécurisé, suivi en temps réel et aucun frais caché. Votre linge est entre de bonnes mains.',
  'vision.excellence_title': 'Excellence',
  'vision.excellence_desc': 'Nous utilisons des équipements de pointe et des produits de première qualité pour offrir un résultat irréprochable. Chaque vêtement mérite une attention particulière.',
  'vision.communauté_title': 'Communauté',
  'vision.communauté_desc': 'Nous croyons en une économie locale forte. Bellissima s\'associe aux artisans et commerçants dakarois pour créer un réseau de services de confiance.',
  'counters.clients': '5 000+ clients satisfaits',
  'counters.machines': '20+ machines haut de gamme',
  'counters.villes': 'Dakar et environs',
  'counters.avis': '4.8/5 — Plus de 1 200 avis',
  'cta.title': 'Prêt à simplifier votre lessive ?',
  'cta.subtitle': 'Rejoignez des milliers de clients satisfaits à Dakar. Déposez votre linge et profitez de votre temps libre.',
  'cta.services': 'Découvrir nos services',
  'cta.contact': 'Nous contacter',
  'nav.home': 'Accueil',
  'nav.services': 'Services',
  'nav.pricing': 'Tarifs',
  'nav.paiement': 'Paiement',
  'nav.contact': 'Contact',
  'nav.fidelite': 'Fidélité',
  'nav.about': 'À propos',
  'services.title': 'Nos Services',
  'services.subtitle': 'Des solutions de lavage professionnelles adaptées à chaque besoin',
  'services.badge': 'Services',
  'services.plans.0.name': 'Lavage Simple',
  'services.plans.0.features.0': 'Lavage en machine haut de gamme',
  'services.plans.0.features.1': 'Séchage inclus',
  'services.plans.0.features.2': 'Pliage soigné',
  'services.plans.0.price_label': 'À partir de',
  'services.plans.0.period': 'par kg',
  'services.plans.0.cta': 'Choisir cette formule',
  'services.plans.1.name': 'Lavage + Repassage',
  'services.plans.1.features.0': 'Lavage professionnel',
  'services.plans.1.features.1': 'Séchage inclus',
  'services.plans.1.features.2': 'Repassage main',
  'services.plans.1.features.3': 'Emballage soigné',
  'services.plans.1.price_label': 'À partir de',
  'services.plans.1.period': 'par kg',
  'services.plans.1.cta': 'Choisir cette formule',
  'services.plans.2.name': 'Nettoyage à Sec',
  'services.plans.2.features.0': 'Nettoyage à sec professionnel',
  'services.plans.2.features.1': 'Détachage spécifique',
  'services.plans.2.features.2': 'Repassage minutieux',
  'services.plans.2.features.3': 'Emballage premium',
  'services.plans.2.features.4': 'Livraison optionnelle',
  'services.plans.2.price_label': 'À partir de',
  'services.plans.2.period': 'par pièce',
  'services.plans.2.cta': 'Choisir cette formule',
  'services.extras.0.title': 'Lavage Express',
  'services.extras.0.desc': 'Votre linge lavé, séché et plié en 45 minutes chrono. Idéal pour les urgences.',
  'services.extras.1.title': 'Service Pliage',
  'services.extras.1.desc': 'Nous plions votre linge avec soin. Reprenez-le directement dans votre panier ou faites-vous livrer.',
  'services.extras.2.title': 'Détergents Premium',
  'services.extras.2.desc': 'Produits hypoallergéniques, parfums de qualité et adoucissants professionnels pour une sensation de fraîcheur durable.',
  'services.extras.3.title': 'Programme Fidélité',
  'services.extras.3.desc': 'Cumulez des points à chaque passage et bénéficiez de réductions exclusives. Plus vous lavez, plus vous économisez.',
  'contact.title': 'Contactez-nous',
  'contact.subtitle': 'Une question ? Une demande spéciale ? Notre équipe est à votre écoute.',
  'contact.info.0.label': 'Adresse',
  'contact.info.0.value': 'Route de la Corniche Ouest, Dakar, Sénégal',
  'contact.info.1.label': 'Téléphone',
  'contact.info.1.value': '+221 33 000 00 00',
  'contact.info.2.label': 'Email',
  'contact.info.2.value': 'contact@bellissima.sn',
  'contact.info.3.label': 'Horaires',
  'contact.info.3.value': 'Lun–Sam : 7h–22h | Dim : 9h–18h',
  'contact.info.4.label': 'WhatsApp',
  'contact.info.4.value': '+221 77 000 00 00',
  'contact.form.name.label': 'Nom complet',
  'contact.form.name.placeholder': 'Votre nom et prénom',
  'contact.form.phone.label': 'Téléphone',
  'contact.form.phone.placeholder': 'Votre numéro de téléphone',
  'contact.form.email.label': 'Email',
  'contact.form.email.placeholder': 'votre@email.com',
  'contact.form.message.label': 'Message',
  'contact.form.message.placeholder': 'Écrivez votre message ici...',
  'contact.form.submit': 'Envoyer le message',
  'contact.form.success': 'Merci ! Votre message a été envoyé avec succès. Nous vous répondrons sous 24h.',
  'contact.form.error': 'Une erreur est survenue lors de l\'envoi. Veuillez réessayer.',
  'contact.form.connection_error': 'Impossible de se connecter au serveur. Vérifiez votre connexion internet.',
  'paiement.title': 'Paiement',
  'paiement.subtitle': 'Payez votre lavage en toute sécurité depuis votre mobile',
  'paiement.badge': 'Paiement en ligne',
  'paiement.machines.0.name': 'Machine Standard',
  'paiement.machines.0.price': '3 000 FCFA',
  'paiement.machines.0.kg': '7 kg',
  'paiement.machines.0.time': '45 min',
  'paiement.machines.1.name': 'Machine Grande Capacité',
  'paiement.machines.1.price': '4 500 FCFA',
  'paiement.machines.1.kg': '12 kg',
  'paiement.machines.1.time': '50 min',
  'paiement.machines.2.name': 'Machine XXL',
  'paiement.machines.2.price': '6 000 FCFA',
  'paiement.machines.2.kg': '18 kg',
  'paiement.machines.2.time': '55 min',
  'paiement.steps.machine': 'Choisir une machine',
  'paiement.steps.payment': 'Effectuer le paiement',
  'paiement.steps.confirm': 'Confirmation',
  'paiement.payment.title': 'Moyen de paiement',
  'paiement.payment.choose_method': 'Choisissez votre moyen de paiement',
  'paiement.options.0.name': 'Wave',
  'paiement.options.0.description': 'Paiement instantané via Wave — rapide et sans frais',
  'paiement.options.1.name': 'Orange Money',
  'paiement.options.1.description': 'Payez avec votre compte Orange Money Sénégal',
  'paiement.options.2.name': 'Free Money',
  'paiement.options.2.description': 'Utilisez Free Money pour un paiement sécurisé',
  'paiement.options.3.name': 'Carte Bancaire',
  'paiement.options.3.description': 'Visa, Mastercard — paiement sécurisé par carte',
  'paiement.options.4.name': 'Espèces en agence',
  'paiement.options.4.description': 'Réservez en ligne et payez directement à la laverie',
  'paiement.confirm.title': 'Confirmation de votre commande',
  'paiement.confirm.machine_label': 'Machine sélectionnée',
  'paiement.confirm.price_label': 'Montant total',
  'paiement.confirm.method_label': 'Moyen de paiement',
  'paiement.confirm.submit': 'Confirmer et payer',
  'paiement.confirm.modify': 'Modifier ma sélection',
  'paiement.back.retour': 'Retour',
  'paiement.choose': 'Choisir',
};

export default FALLBACK_FR;
